### PR TITLE
Login Page + Admin Inbox

### PR DESCRIPTION
**Pull request by isabellarojasg**
This is how the login page looks like atm. Let me know if I should add/delete anything :)

Screen Shot 2023-05-30 at 5 05 26 PM

### CODE REVIEW

**Comment by vijaivir** [comment]
The layout looks pretty neat! Could you pull all changes so that this pr is up to date with main. 

Regarding the layout, remember to add the login button. 
Screenshot 2023-05-29 at 11 31 03 PM

**Comment by markmotet** [comment]
Hey Isabella we merged the AdminNavbar and ProfessorNavbar into one Navbar. Could you add your login to Navbar instead of the old AdminNavbar?

**Comment by isabellarojasg** [comment]
> Hey Isabella we merged the AdminNavbar and ProfessorNavbar into one Navbar. Could you add your login to Navbar instead of the old AdminNavbar?

@markmotet Added login to Navbar! Let me know if there is anything else I should add

**Review by vijaivir — APPROVED** [review]
Nice work!

**Pull request merged**
